name: "afdian-action"
author: yiyungent
description: "爱发电 自动生成赞助页面 | GitHub Action"


inputs:
  # gh_token:
  #   description: "GitHub access token with Repo scope"
  #   default: ${{ github.token }}
  #   required: true

  # repository:
  #   description: "Your GitHub repository"
  #   default: ${{ github.repository }}
  #   required: false

  template_filePath:
    description: "template_filePath"
    default: ".github/afdian-action.cshtml"
    required: false

  target_filePath:
    description: "target_filePath"
    default: "README.md"
    required: false

  start_flag:
    description: "start_flag"
    default: "<!-- AFDIAN-ACTION:START -->"
    required: false
  
  end_flag:
    description: "end_flag"
    default: "<!-- AFDIAN-ACTION:END -->"
    required: false

  afdian_userId:
    description: "afdian_userId"
    default: ""
    required: true
  
  afdian_token:
    description: "afdian_token"
    default: ""
    required: true

  afdian_debug:
    description: "debug for afdian-action"
    default: false
    required: false


outputs:
  afdian_result:
    description: "afdian_result"
    value: "暂时不输出"


runs:
  using: "composite"
  steps:

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    
    - name: Run
      # The command you want to run. This can be inline or a script in your action repository:
      # ${{ github.action_path }} or $GITHUB_ACTION_PATH
      # run: ${{ github.action_path }}/test/script.sh
      # env: |  # 失败报错
      #   INPUT_AFDIAN_TOKEN: ${{ inputs.afdian_token }}
      #   INPUT_AFDIAN_USERID: ${{ inputs.afdian_userId }}
      #   INPUT_TEMPLATE_FILEPATH: ${{ github.workspace }}/${{ inputs.template_filePath }}
      #   INPUT_TARGET_FILEPATH: ${{ github.workspace }}/${{ inputs.target_filePath }}
      #   INPUT_START_FLAG: ${{ inputs.start_flag }}
      #   INPUT_END_FLAG: ${{ inputs.end_flag }}
      #   INPUT_AFDIAN_DEBUG: ${{ inputs.afdian_debug }}
      run: | 
        export INPUT_AFDIAN_USERID=${{ inputs.afdian_userId }}
        export INPUT_AFDIAN_TOKEN=${{ inputs.afdian_token }}
        export INPUT_TEMPLATE_FILEPATH=${{ github.workspace }}/${{ inputs.template_filePath }}
        export INPUT_TARGET_FILEPATH=${{ github.workspace }}/${{ inputs.target_filePath }}
        export INPUT_START_FLAG=${{ inputs.start_flag }}
        export INPUT_END_FLAG=${{ inputs.end_flag }}
        export INPUT_AFDIAN_DEBUG=${{ inputs.afdian_debug }}
        cd ${{ github.action_path }}/src/Afdian.Action
        dotnet run
      shell: bash


branding:
  icon: "heart"
  color: "red"
