name: Test Action

on:
  push:
    branches: [main] # 注意更改为你的 branch, 例如 master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Action
        id: test
        uses: ./ # Uses an action in the root directory
        with:
          # 默认为空, 即为仓库根目录
          scan_directory: "test/coo.Tests/TestData"
          # 多个路径之间用 英文逗号 , 隔开, 用相对于仓库根目录的 相对路径
          ignore_paths: "test/coo.Tests/TestData/IgnoreDir1,test/coo.Tests/TestData/IgnoreDir2,test/coo.Tests/TestData/images/1.png"
          cia_debug: true

      # Use the output from the `test` step
      - name: Get the output image_report
        run: |
          echo "The output was ${{ steps.test.outputs.image_report_clear }}"
          echo "The output was ${{ steps.test.outputs.image_report_check }}"
        shell: bash
